version: '3.8'

services:
  # SQL Server-tjänst
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: merchstore-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongP@ssw0rd!  # OBS: Använd en säkrare lösenord i produktion
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - merchstore-network

networks:
  merchstore-network:
    driver: bridge

volumes:
  sqlserver-data: