# .github/workflows/deploy.yml
name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: codecrasher2/merchstore
  AZURE_REGION: swedencentral

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set Version
        id: version
        run: echo "version=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}

  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Container Apps
        id: deploy
        run: |
          az containerapp update \
            --name merchstorecontainer \
            --resource-group MerchStoreRG \
            --image ${{ env.DOCKER_IMAGE }}:${{ needs.build.outputs.version }} \
            --min-replicas 1 \
            --max-replicas 3 \
            --cpu 0.5 \
            --memory 1.0 \
          
          az containerapp ingress enable \
            --name merchstorecontainer \
            --resource-group MerchStoreRG \
            --type external \
            --target-port 8080\
            --allow-insecure 

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          
          # Hämta app URL
          url=$(az containerapp show \
            --name merchstorecontainer \
            --resource-group MerchStoreRG \
            --query properties.configuration.ingress.fqdn \
            -o tsv)
          
          echo "Application URL: https://$url"
          
          # Verifiera deployment
          if curl -s --fail "https://$url/health"; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment verification failed"
            exit 1
          fi