# .github/workflows/deploy.yml
name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: codecrasher2/merchstore
  AZURE_REGION: swedencentral

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set Version
        id: version
        run: echo "version=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Container App
        run: |
          az containerapp update \
            --name merchstorecontainer \
            --resource-group MerchStoreRG \
            --image ${{ env.DOCKER_IMAGE }}:${{ needs.build.outputs.version }} \
            --min-replicas 1 \
            --max-replicas 3 \
            --cpu 0.5 \
            --memory 1.0 \
            --set-env-vars ASPNETCORE_URLS=http://+:8080

      - name: Enable Ingress
        run: |
          # Kolla om ingress redan är konfigurerad
          ingress_status=$(az containerapp show \
            --name merchstorecontainer \
            --resource-group MerchStoreRG \
            --query "properties.configuration.ingress.external" \
            -o tsv)
          
          if [ "$ingress_status" != "true" ]; then
            echo "Enabling external ingress..."
            az containerapp ingress enable \
              --name merchstorecontainer \
              --resource-group MerchStoreRG \
              --type external \
              --target-port 8080 \
              --transport auto
          
            # Vänta lite så att ingress konfigureras
            sleep 10
          else
            echo "Ingress already enabled"
          fi

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 20
          
          # Hämta app URL
          url=$(az containerapp show \
            --name merchstorecontainer \
            --resource-group MerchStoreRG \
            --query "properties.configuration.ingress.fqdn" \
            -o tsv)
          
          echo "Application URL: https://$url"
          
          # Enkel kontroll
          if [ -n "$url" ]; then
            echo "✅ Deployment successful!"
            echo "Your app is available at: https://$url"
          else
            echo "⚠️ Could not get URL"
            # Kolla status
            az containerapp show \
              --name merchstorecontainer \
              --resource-group MerchStoreRG \
              --query "properties.provisioningState" \
              -o tsv
          fi